name: Node js app deploy to EKS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' # default is latest stable
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: githublearning
        BUILD_TAG: ${{ github.run_number }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$BUILD_TAG .
        docker push $REGISTRY/$REPOSITORY:$BUILD_TAG

    - name: Update kube config
      run: aws eks update-kubeconfig --name githublearning
    
    - name: Deploy to EKS
      run: |
        echo ${{ github.run_number }}
        sed -e "s|IMAGE_TAG|${{ github.run_number }}|g" deployment.yaml | kubectl apply -f -
        kubectl apply -f service.yaml